### PR TITLE
Create main

### PR DESCRIPTION
**Pull request by Zilola-Nazarova**
Here I have created main.rb file.

Main.rb file has methods:
`main` - shows the greeting message
`show_options` - shows the options available

`main.rb` file calls `main` method. Now our app can be invoked in command line:
image

### CODE REVIEW

**Review by hetrox8 — COMMENTED** [review]
Hi @Zilola-Nazarova Good job implementing the Task requirement . I would kindly suggest you work on the rubocop.yml

**Review by hetrox8 — CHANGES_REQUESTED** [review]
Good job so far kindly work on rubocop linters.

**Comment by Zilola-Nazarova** [comment]
@hetrox8 
But there are no rubocop errors 🙂

**Comment by Zilola-Nazarova** [comment]
I'm sorry @hetrox8 I think my branch wasn't fully pushed that's why you saw these linter errors 😄

**Pull request merged**
